var STATIC_INDEX = [
  // ===== BLOG HG WIKI =====
  {title: 'HG Wiki', url: 'https://www.hectorgonzalez.ar/', content: 'Portal principal de HG Wiki', type: 'blog', category: 'General'},
  
  // ===== GOBIERNO =====
  {title: 'Gobierno de Córdoba', url: 'https://www.cba.gov.ar/', content: 'Portal oficial del Gobierno de la Provincia de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'Municipalidad de Córdoba', url: 'https://cordoba.gob.ar/', content: 'Gobierno de la Ciudad de Córdoba - Trámites y servicios', type: 'external', category: 'Gobierno'},
  {title: 'Legislatura de Córdoba', url: 'https://legislaturacba.gob.ar/', content: 'Poder Legislativo de la Provincia de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'Ciudadano Digital (CIDI)', url: 'https://cidi.cba.gov.ar/portal-publico/', content: 'Trámites digitales del Gobierno de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'Rentas Córdoba', url: 'https://www.rentascordoba.gob.ar/', content: 'Pago de impuestos provinciales', type: 'external', category: 'Gobierno'},
  {title: 'Bancor', url: 'https://www.bancor.com.ar/', content: 'Banco de la Provincia de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'EPEC', url: 'https://www.epec.com.ar/', content: 'Empresa Provincial de Energía de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'APROSS', url: 'https://www.apross.gov.ar/', content: 'Obra Social de empleados públicos de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'Caja de Jubilaciones', url: 'https://cajajubilaciones.cba.gov.ar/', content: 'Jubilaciones y pensiones de Córdoba', type: 'external', category: 'Gobierno'},
  {title: 'UEPC', url: 'https://uepc.org.ar/', content: 'Unión de Educadores de la Provincia de Córdoba', type: 'external', category: 'Gobierno'},
  
  // ===== UNIVERSIDADES =====
  {title: 'UNC - Universidad Nacional de Córdoba', url: 'https://www.unc.edu.ar/', content: 'Universidad Nacional de Córdoba', type: 'external', category: 'Universidad'},
  {title: 'UPC - Universidad Provincial de Córdoba', url: 'https://www.upc.edu.ar/', content: 'Universidad Provincial de Córdoba', type: 'external', category: 'Universidad'},
  {title: 'UCC - Universidad Católica de Córdoba', url: 'https://www.ucc.edu.ar/', content: 'Universidad Católica de Córdoba', type: 'external', category: 'Universidad'},
  {title: 'Universidad Siglo 21', url: 'https://21.edu.ar/', content: 'Universidad Siglo 21 - Educación a distancia', type: 'external', category: 'Universidad'},
  {title: 'UNVM - Universidad Nacional de Villa María', url: 'https://www.unvm.edu.ar/', content: 'Universidad Nacional de Villa María', type: 'external', category: 'Universidad'},
  {title: 'Universidad Blas Pascal | UBP', url: 'https://www.ubp.edu.ar/', content: 'Saber y Saber Hacer.', type: 'external', category: 'Universidad'},
  {title: 'Universidad Tecnologica de Cordoba - UTN', url: 'https://www.frc.utn.edu.ar/', content: 'Universidad Tecnologica de Córdoba', type: 'external', category: 'Universidad'},
  
  // ===== EDUCACIÓN =====
  {title: 'UNCiencia', url: 'https://unciencia.unc.edu.ar/', content: 'Agencia de comunicación científica de la UNC', type: 'external', category: 'Educación'},
  {title: 'Museo de Antropología UNC', url: 'https://museoantropologia.unc.edu.ar/', content: 'Museo de Antropología de la UNC', type: 'external', category: 'Educación'},
  {title: 'ISEP', url: 'https://isep-cba.edu.ar/web/', content: 'Instituto Superior de Estudios Pedagógicos', type: 'external', category: 'Educación'},
  {title: 'ISCET', url: 'https://www.iscet.edu.ar/', content: 'Instituto Superior de Ciencias Económicas', type: 'external', category: 'Educación'},
  {title: 'Alianza Francesa Córdoba', url: 'https://alianzafrancesacba.org.ar/', content: 'Cursos de francés y programación cultural', type: 'external', category: 'Educación'},
  {title: 'Escuelas Pías de Córdoba', url: 'https://escuelaspiasdecordoba.edu.ar/', content: 'Institución educativa en Barrio Gral Paz', type: 'external', category: 'Educación'},
  {title: 'El Historiador - Felipe Pigna', url: 'https://elhistoriador.com.ar/', content: 'Historia Argentina y recursos educativos', type: 'external', category: 'Educación'},
  
  // ===== MUSEOS =====
  {title: 'Museo Emilio Caraffa', url: 'https://www.museocaraffa.org.ar/', content: 'Museo de Bellas Artes de Córdoba', type: 'external', category: 'Museo'},
  {title: 'Museo Palacio Ferreyra', url: 'https://www.facebook.com/museoevitacioferreyra', content: 'Museo Superior de Bellas Artes Evita', type: 'external', category: 'Museo'},
  {title: 'Museo Genaro Pérez', url: 'https://museogenaroperez.wordpress.com/', content: 'Museo de Artes Visuales de Córdoba', type: 'external', category: 'Museo'},
  {title: 'Museo del Cuarteto', url: 'https://www.facebook.com/Museodelcuarteto', content: 'Museo dedicado al género musical cuarteto', type: 'external', category: 'Museo'},
  {title: 'Cripta Jesuítica', url: 'https://criptajesuitica.wordpress.com/', content: 'Museo histórico jesuita', type: 'external', category: 'Museo'},
  {title: 'Estancia de Jesús María', url: 'https://linktr.ee/estanciadejesusmaria/', content: 'Museo Jesuítico Nacional', type: 'external', category: 'Museo'},
  {title: 'Museo Rocsen', url: 'https://www.facebook.com/BibliotecaPopularSarmiento', content: 'Museo en Nono, Traslasierra', type: 'external', category: 'Museo'},
  {title: 'Casa Museo Lino Spilimbergo', url: 'https://www.facebook.com/casamuseospilimbergo', content: 'Museo municipal de artes visuales en Unquillo', type: 'external', category: 'Museo'},
  {title: 'Casa Museo Fernando Fader', url: 'https://cultura.cba.gov.ar/casa-museo-fernando-fader/', content: 'Museo del artista plástico en Ischilín', type: 'external', category: 'Museo'},
  {title: 'Museo Malvinas', url: 'https://museomalvinas.cultura.gob.ar/', content: 'Museo de la Memoria de Malvinas', type: 'external', category: 'Museo'},
  {title: 'Estancia Jesuítica Alta Gracia', url: 'https://museogalloymonteano.cultura.gob.ar/', content: 'Sitio oficial del Museo Nacional Estancia Jesuítica de Alta Gracia y Casa del Virrey Liniers.', category: 'Museo'},
  {title: 'Estancia Jesuítica Caroya', url: 'https://cultura.cba.gov.ar/estancia-jesuitica-caroya/', content: 'Primer exponente productivo del sistema jesuítico, clave en la historia textil y de la comunidad de Colonia Caroya.', category: 'Museo'},
  {title: 'Casa Museo Atahualpa Yupanqui', url: 'https://www.atahualpayupanqui.org.ar/', content: 'Creando bienes culturales, proyectos de investigación, difusión y conservación de nuestras manifestaciones culturales autóctonas.', category: 'Museo'},
  {title: 'Museo de Motos y Bicicletas', url: 'https://www.facebook.com/museo.demotos.3', content: '📢 Abierto de viernes a domingos de 9 a 12 y de 15 a 18Btlme Jaime 1293 La Cumbre Córdoba', category: 'Museo'},
  {title: 'Museo de Municiones', url: 'https://www.facebook.com/MuseoDeMunicionesdonHectorPascualRadicci', content: 'Esta abierto al público todo el año, incluso los feriados!!! - Mina Clavero', category: 'Museo'},
  {title: 'Museo Villa Allende', url: 'https://www.facebook.com/museo.historico.cultural.villa.allende/', content: 'Desde nuestro espacio, que en este 2026 cumple 20 años, agradecemos a la comunidad por ayudarnos a construir, a encontrarnos, a fomentar la participación y la memoria.', category: 'Museo'},
  { title: 'Museo Fundacion MACU - Unquillo', url: 'https://www.facebook.com/museo.historico.cultural.villa.allende/', content: 'Se trata de mostrar la Institución del Museo de Arte Contemporáneo de Unquillo - MACU,', category: 'Museo'},
  
  // ===== CULTURA =====
  {title: 'Agenda Cultural Córdoba', url: 'https://cultura.cba.gov.ar/', content: 'Eventos, museos, teatros y actividades culturales', type: 'external', category: 'Cultura'},
  {title: 'Centro Cultural Casa de Pepino', url: 'https://cultura.cordoba.gob.ar/espacio_cultural/centro-cultural-casa-de-pepino/', content: 'Centro cultural de artes visuales', type: 'external', category: 'Cultura'},
  {title: 'Centro Cultural Discepolín', url: 'https://www.facebook.com/discepolincc', content: 'Centro de cultura popular en B° Güemes', type: 'external', category: 'Cultura'},
  {title: 'Centro Cultural Miguel Iriarte', url: 'https://www.facebook.com/centroculturalsanvicente', content: 'Centro cultural en San Vicente', type: 'external', category: 'Cultura'},
  {title: 'Centro Cultural Manuel de Falla', url: 'https://www.facebook.com/CentroCulturalManueldeFalla', content: 'Academia de Música Municipal', type: 'external', category: 'Cultura'},
  {title: 'Galería Arte o Nada', url: 'https://www.facebook.com/arteonada', content: 'Galería de arte y eventos culturales en Unquillo', type: 'external', category: 'Cultura'},
  {title: 'Arte Cba', url: 'https://artecba.com/', content: 'Espacio para artistas y público', type: 'external', category: 'Cultura'},
  {title: 'Feria Paseo de las Artes', url: 'https://www.facebook.com/paseodelasartescordoba', content: 'Feria de artesanías en Güemes', type: 'external', category: 'Cultura'},
  {title: 'Teatro del Libertador', url: 'https://linktr.ee/teatrodellibertadorsanmartin', content: 'Teatro histórico de Córdoba', type: 'external', category: 'Cultura'},
  {title: 'Teatro Ciudad de las Artes', url: 'https://linktr.ee/teatrociudadelasartes', content: 'Teatro en la UPC', type: 'external', category: 'Cultura'},
  {title: 'Teatro La Llave', url: 'https://teatrolallave.com/', content: 'Multiplataforma cultural', type: 'external', category: 'Cultura'},
  {title: 'Cine Teatro Municipal Unquillo', url: 'https://cineunquillo.com.ar/', content: 'Venta de entradas', type: 'external', category: 'Cultura'},
  {title: 'Escuela de Comedia Musical', url: 'https://www.comediamusicalcordoba.com/', content: 'Formación en teatro, canto y baile', type: 'external', category: 'Cultura'},
  {title: 'Centro Cultural Córdoba', url: 'https://cultura.cba.gov.ar/espacios-culturales/centro-cultural-cordoba/', content: 'Espacio vanguardista que alberga el Archivo Histórico, muestras de arte, ciclos de cine y eventos culturales.', category: 'Cultura'},
  {title: 'Archivo Provincial de la Memoria', url: 'https://espaciosmemoriacordoba.com.ar/apm/', content: 'Derribando Olvidos. Construyendo Memorias', category: 'Cultura'},

  
  // ===== MEDIOS =====
  {title: 'La Voz del Interior', url: 'https://www.lavoz.com.ar/', content: 'Principal diario de Córdoba', type: 'external', category: 'Medios'},
  {title: 'Cadena 3', url: 'https://cadena3.com/', content: 'Radio y portal de noticias', type: 'external', category: 'Medios'},
  {title: 'El Doce TV', url: 'https://eldoce.tv/', content: 'Canal 12 de Córdoba', type: 'external', category: 'Medios'},
  {title: 'Perfil Córdoba', url: 'https://www.perfil.com/seccion/cordoba', content: 'Noticias desde Córdoba', type: 'external', category: 'Medios'},
  {title: 'FOPEA', url: 'https://fopea.org/', content: 'Foro de Periodismo Argentino', type: 'external', category: 'Medios'},
  {title: 'En Redacción', url: 'https://enredaccion.com.ar/', content: 'Periodismo de investigación local', type: 'external', category: 'Medios'},
  {title: 'La Tinta', url: 'https://latinta.com.ar/', content: 'Periodismo cooperativo', type: 'external', category: 'Medios'},
  {title: 'Política Córdoba Verdad', url: 'https://politicacordobaverdad.com.ar/', content: 'Noticias políticas de Córdoba', type: 'external', category: 'Medios'},
  {title: 'El Puntal', url: 'https://www.puntal.com.ar/', content: 'Noticias de Río Cuarto y región', type: 'external', category: 'Medios'},
  {title: 'Córdoba Times', url: 'https://www.cordobatimes.com/', content: 'Portal independiente de noticias', type: 'external', category: 'Medios'},
  {title: 'Hoy Día Córdoba', url: 'https://hoydia.com.ar/', content: 'Noticias actualizadas de Córdoba', type: 'external', category: 'Medios'},
  {title: 'Diario Resumen', url: 'https://diarioresumen.com.ar/', content: 'Noticias de Pilar', type: 'external', category: 'Medios'},
  {title: 'Ruta 9 Noticias', url: 'https://ruta9noticias.com/', content: 'Noticias del Departamento Río Segundo', type: 'external', category: 'Medios'},
  {title: 'Diario Sumario', url: 'https://diariosumario.com.ar/', content: 'Noticias de Alta Gracia', type: 'external', category: 'Medios'},
  {title: 'Striptease del Poder', url: 'https://stripteasedelpoder.com/', content: 'Periodismo de investigación', type: 'external', category: 'Medios'},
  {title: 'Prensa Red', url: 'https://prensared.org.ar/', content: 'Agencia de Noticias del CISPREN', type: 'external', category: 'Medios'},
  {title: 'Diario Tortuga', url: 'https://diariotortuga.com/', content: 'Cooperativa autogestionada', type: 'external', category: 'Medios'},
  {title: 'Diario Alfil', url: 'https://diarioalfil.com.ar/', content: 'Noticias y análisis político', type: 'external', category: 'Medios'},
  {title: 'Radio Suquía 96.5', url: 'https://suquia.ar/vivo/', content: 'FM Suquía', type: 'external', category: 'Medios'},
  {title: 'FM Sierras Chicas 104.5', url: 'https://fmsierraschicas.com/', content: 'Radio Turismo Río Ceballos', type: 'external', category: 'Medios'},
  {title: 'Radio Jaja 105.3', url: 'https://www.radiojaja.com.ar/', content: 'Radio de Sierras Chicas', type: 'external', category: 'Medios'},
  {title: 'FM Sol Río Tercero', url: 'https://fmsolriotercero.esenvivo.com.ar/', content: 'Radio de Río Tercero', type: 'external', category: 'Medios'},
  {title: 'DEMENDIOLAZA', url: 'https://demendiolaza.com.ar/', content: 'Portal de Noticias y Radio', type: 'external', category: 'Medios'},
  {title: 'TYC Sports', url: 'https://www.tycsports.com/', content: 'TyC Sports - Las noticias de deportes del canal líder en Argentina ', category: 'Medios'},
  { title: 'La Nueva Mañana', url: 'https://lmdiario.com.ar/', content: 'Un diario cordobés con el compromiso de hacer periodismo responsable, transparente y con agenda propia.', category: 'Medio'},
  
  // ===== BIBLIOTECAS =====
  {title: 'Biblioteca Nacional Mariano Moreno', url: 'https://www.bn.gov.ar/', content: 'Biblioteca Nacional de Argentina', type: 'external', category: 'Biblioteca'},
  {title: 'Biblioteca Popular Sarmiento', url: 'https://www.facebook.com/BibliotecaPopularSarmiento', content: 'Biblioteca en Río Ceballos', type: 'external', category: 'Biblioteca'},
  {title: 'Biblioteca Urquiza', url: 'https://bibliotecaurquiza.org.ar/', content: 'Biblioteca Popular en Río Tercero', type: 'external', category: 'Biblioteca'},
  {title: 'Biblioteca Popular Casa del Pueblo', url: 'https://www.facebook.com/biblioteca.casadelpueblo', content: 'Biblioteca comunitaria', type: 'external', category: 'Biblioteca'},
  {title: 'Biblioteca Popular Tere Andruetto', url: 'https://www.facebook.com/bbpptereandruetto', content: 'Biblioteca en Unquillo', type: 'external', category: 'Biblioteca'},
  {title: 'CEH Segreti', url: 'https://cehsegreti.org.ar/', content: 'Centro de Estudios Históricos - CONICET', type: 'external', category: 'Biblioteca'},
  {title: 'Babilonia Literaria', url: 'https://babilonialiteraria.com.ar/', content: 'Portal literario de Córdoba', type: 'external', category: 'Biblioteca'},
  { title: 'Biblioteca Mayor de la UNC', url: 'https://bmayor.unc.edu.ar/', content: 'Una de las bibliotecas universitarias más antiguas del país, con un fondo bibliográfico histórico invaluable.', category: 'Biblioteca'}, 
  { title: 'Biblioteca Córdoba', url: 'https://cultura.cba.gov.ar/biblioteca-cordoba/', content: 'Biblioteca pública provincial, espacio de presentación de libros, talleres literarios y resguardo de autores locales.', category: 'Biblioteca'},
  
  // ===== ENTRETENIMIENTO =====
  {title: 'Cosquín Rock', url: 'https://cosquinrock.net/', content: 'Festival de rock más importante del país', type: 'external', category: 'Entretenimiento'},
  {title: 'Festival de Cosquín', url: 'https://aquicosquin.com.ar/', content: 'Festival Nacional de Folklore', type: 'external', category: 'Entretenimiento'},
  {title: 'Festival de Jesús María', url: 'https://festival.org.ar/', content: 'Festival de jineteada y destrezas gauchas', type: 'external', category: 'Entretenimiento'},
  {title: 'Festival de Peñas Villa María', url: 'https://anfi.villamaria.gob.ar/', content: 'Festival Internacional de Peñas', type: 'external', category: 'Entretenimiento'},
  {title: 'Parque Quebrada del Condorito', url: 'https://quebradadelcondorito.com.ar/', content: 'Parque Natural y trekking', type: 'external', category: 'Entretenimiento'},
  {title: 'Quaras Parque de Montaña', url: 'https://quaras.com.ar/', content: 'Parque de montaña en Villa General Belgrano', type: 'external', category: 'Entretenimiento'},
  {title: 'Super Park', url: 'https://super-park.com.ar/index.html', content: 'Parque de diversiones en Parque Sarmiento', type: 'external', category: 'Entretenimiento'},
  {title: 'Plaza de la Música', url: 'https://plazadelamusica.com/', content: 'Espacio para arte y música', type: 'external', category: 'Entretenimiento'},
  {title: 'La Mona Museo Bar', url: 'https://lamonamuseobar.com/', content: 'Museo interactivo del cuarteto', type: 'external', category: 'Entretenimiento'},
  {title: 'Only in Córdoba', url: 'https://onlyincordoba.com.ar/', content: 'Agenda cultural y planazos', type: 'external', category: 'Entretenimiento'},
  {title: 'Complejo Cinerama', url: 'https://complejocinerama.com.ar/', content: 'Salas de cine en Av. Colón', type: 'external', category: 'Entretenimiento'},
  {title: 'Cineclub Municipal Hugo del Carril', url: 'https://cineclubmunicipal.org.ar/', content: 'Cineclub municipal', type: 'external', category: 'Entretenimiento'},
  {title: 'Cines Gran Rex', url: 'http://cinesgranrex.com.ar/', content: 'Cartelera Promociones 4D Cumpleaños Candy ¡VAMOS AL REX!', category: 'Entretenimiento'},

  // ===== COMERCIO =====
  {title: 'Paseo del Jockey', url: 'https://paseodeljockey.com/', content: 'Centro Comercial zona sur de Córdoba', type: 'external', category: 'Comercio'},
  {title: 'VAS Shopping', url: 'https://vasshopping.com.ar/', content: 'Villa Allende Shopping', type: 'external', category: 'Comercio'},
  {title: 'WO Carlos Paz', url: 'https://wocarlospaz.com/', content: 'Shopping en Villa Carlos Paz', type: 'external', category: 'Comercio'},
  {title: 'Nuevo Centro Shopping', url: 'https://www.nuevocentro.com.ar/', content: ' Nuevocentro Shopping se destaca entre los centros comerciales de Córdoba y del país.', category: 'Comercio'},
  {title: 'Cordoba Shopping', url: 'https://www.cordobashopping.com.ar/', content: 'El plan perfecto para ir a tu ritmo, encontrar lo que buscás ', category: 'Comercio'},
  
  // ===== DEPORTES =====
  {title: 'Córdoba Lawn Tenis Club', url: 'https://www.cordobalawntenis.com.ar/', content: 'Club de tenis tradicional', type: 'external', category: 'Deportes'},
  {title: 'Canal Showsport', url: 'https://canalshowsport.com.ar/', content: 'Canal de deportes', type: 'external', category: 'Deportes'},
  
  // ===== GENERAL =====
  {title: 'Wikipedia', url: 'https://es.wikipedia.org/', content: 'Enciclopedia libre', type: 'external', category: 'General'},
  {title: 'Servicio Meteorológico Nacional', url: 'https://smn.gob.ar/', content: 'Pronóstico del tiempo', type: 'external', category: 'General'},
  {title: 'APADIM Córdoba', url: 'https://www.apadim.org.ar/', content: 'Inclusión y derechos', type: 'external', category: 'General'},
  {title: 'Portal Memoria Córdoba', url: 'https://espaciosmemoriacordoba.com.ar/', content: 'Espacios de Memoria y DD.HH.', type: 'external', category: 'General'},
  {title: 'Mercado Libre Argentina', url: 'https://www.mercadolibre.com.ar/', content: 'Plataforma de compras', type: 'external', category: 'General'},
  {title: 'Autoentrada', url: 'https://ventas.autoentrada.com/taxons/teatro', content: 'Venta de entradas para eventos', type: 'external', category: 'General'},
  {title: 'DEPORTICK', url: 'https://www.deportick.com/', content: 'Venta de tickets deportivos', type: 'external', category: 'General'},
  {title: 'Neurona Comercial', url: 'https://neuronacomercial.com.ar/', content: 'Consultoría en marketing digital', type: 'external', category: 'General'},
  {title: 'Alternativa Teatral', url: 'https://publico.alternativateatral.com/', content: 'Venta de entradas para teatro independiente', type: 'external', category: 'General'}
  ];
