{
  "version": 21,
  "generated": "2026-05-16T00:00:00.000Z",
  "totalItems": 467,
  "items": [
    {
      "title": "Wikipedia",
      "url": "https://es.wikipedia.org/",
      "content": "Enciclopedia online de acceso libre y colaborativo.",
      "thumbnail": "",
      "labels": ["historia", "informacion", "enciclopedia"],
      "type": "external",
      "source": "🔗 educación",
      "category": "educación",
      "date": "2026-05-16"
    },
    {
      "title": "Estancia de Jesus Maria",
      "url": "https://linktr.ee/estanciadejesusmaria/",
      "content": "Museo Jesuitico Nacional",
      "thumbnail": "",
      "labels": ["Museo", "Jesuitas", "Jesus Maria"],
      "type": "external",
      "source": "🔗 educacion",
      "category": "educacion",
      "date": "2026-05-16"
    },
    {
      "title": "Museo del Cuarteto",
      "url": "https://www.facebook.com/Museodelcuarteto",
      "content": "El cuarteto tiene esa magia única: tiene el peso de la historia y el respeto de ser un folklore con más de ocho décadas",
      "thumbnail": "",
      "labels": ["Cuarteto", "Musica", "Museo", "Cordoba"],
      "type": "external",
      "source": "🔗 Museo de Musica",
      "category": "Museo de Musica",
      "date": "2026-05-16"
    },
    {
      "title": "Diario Resumen",
      "url": "https://diarioresumen.com.ar/",
      "content": "Las noticias mas importantes de Pilar",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Pilar, Cordoba"],
      "type": "external",
      "source": "🔗 Medios de Comunicacion",
      "category": "Medios de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Cripta Jesuítica",
      "url": "https://criptajesuitica.wordpress.com/",
      "content": "El protagonismo del museo lo asume el espacio y su propia historia.",
      "thumbnail": "",
      "labels": ["Jesuitas", "catolico", "Museo", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacios Históricos",
      "category": "Espacios Históricos",
      "date": "2026-05-16"
    },
    {
      "title": "Museo Rocsen",
      "url": "https://www.facebook.com/BibliotecaPopularSarmiento",
      "content": "Organización que se encarga del Museo Rocsen, ubicado en Nono, Córdoba.",
      "thumbnail": "",
      "labels": ["Traslasierra", "Museo", "Nono"],
      "type": "external",
      "source": "🔗 Museo",
      "category": "Museo",
      "date": "2026-05-16"
    },
    {
      "title": "Museo Emilio Caraffa",
      "url": "https://www.museocaraffa.org.ar/",
      "content": "Exposiciones que reflexionan sobre memoria, politica, literatura y arte contemporaneo.",
      "thumbnail": "",
      "labels": ["Museo", "Bellas Artes", "literatura", "Cordoba"],
      "type": "external",
      "source": "🔗 museo",
      "category": "museo",
      "date": "2026-05-16"
    },
    {
      "title": "Centro Cultural Casa de Pepino",
      "url": "https://cultura.cordoba.gob.ar/espacio_cultural/centro-cultural-casa-de-pepino/",
      "content": "Su mayor afluencia esta conformada por seguidores del arte visual.",
      "thumbnail": "",
      "labels": ["Centro Cultural", "Bellas Artes", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacio Cultural",
      "category": "Espacio Cultural",
      "date": "2026-05-16"
    },
    {
      "title": "Museo Palacio Ferreyra",
      "url": "https://www.facebook.com/museoevitacioferreyra",
      "content": "El Palacio Ferreyra, hoy Museo Superior de Bellas Artes Evita en Cordoba.",
      "thumbnail": "",
      "labels": ["Bellas Artes", "Museo", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacios Históricos",
      "category": "Espacios Históricos",
      "date": "2026-05-16"
    },
    {
      "title": "El Historiador - Felipe Pigna",
      "url": "https://elhistoriador.com.ar/",
      "content": "Web de Historia Argentina y mundial. Recursos educativos.",
      "thumbnail": "",
      "labels": ["historia", "argentina", "educacion", "felipe pigna"],
      "type": "external",
      "source": "🔗 educacion",
      "category": "educacion",
      "date": "2026-05-16"
    },
    {
      "title": "Universidad Provincial de Cordoba - UPC",
      "url": "https://www.upc.edu.ar/",
      "content": "La Universidad Provincial de Cordoba es publica, administrada por el estado provincial.",
      "thumbnail": "",
      "labels": ["Universidad", "educacion", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacios Universitarios",
      "category": "Espacios Universitarios",
      "date": "2026-05-16"
    },
    {
      "title": "UNCiencia",
      "url": "https://unciencia.unc.edu.ar/",
      "content": "Agencia oficial de comunicacion publica de la ciencia y la tecnologia de la UNC.",
      "thumbnail": "",
      "labels": ["Ciencia", "UNC", "Cordoba"],
      "type": "external",
      "source": "🔗 educacion",
      "category": "educacion",
      "date": "2026-05-16"
    },
    {
      "title": "En Redaccion",
      "url": "https://enredaccion.com.ar/",
      "content": "Medio nativo digital especializado en periodismo de investigacion local y regional.",
      "thumbnail": "",
      "labels": ["periodismo", "Diario Digital", "Cordoba"],
      "type": "external",
      "source": "🔗 Medios de Comunicación",
      "category": "Medios de Comunicación",
      "date": "2026-05-16"
    },
    {
      "title": "Museo de Antropologia - UNC",
      "url": "https://museoantropologia.unc.edu.ar/",
      "content": "Investigaciones sobre los primeros habitantes de la region.",
      "thumbnail": "",
      "labels": ["Antropologia", "Universidad", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacios Universitarios",
      "category": "Espacios Universitarios",
      "date": "2026-05-16"
    },
    {
      "title": "La Tinta",
      "url": "https://latinta.com.ar/",
      "content": "Periodismo cooperativo de referencia en cronicas sociales.",
      "thumbnail": "",
      "labels": ["Periodismo", "Informacion", "Cordoba"],
      "type": "external",
      "source": "🔗 Medios de Comunicación",
      "category": "Medios de Comunicación",
      "date": "2026-05-16"
    },
    {
      "title": "Biblioteca Popular Sarmiento",
      "url": "https://www.facebook.com/BibliotecaPopularSarmiento",
      "content": "Espacio cultural y biblioteca popular comunitaria.",
      "thumbnail": "",
      "labels": ["biblioteca", "Libros", "Rio Ceballos"],
      "type": "external",
      "source": "🔗 Educación",
      "category": "Educación",
      "date": "2026-05-16"
    },
    {
      "title": "El Puntal",
      "url": "https://www.puntal.com.ar/",
      "content": "Portal líder en noticias de Río Cuarto y la región sur de Córdoba.",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Rio Cuarto"],
      "type": "external",
      "source": "🔗 Medios de comunicacion",
      "category": "Medios de comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Cordoba Times",
      "url": "https://www.cordobatimes.com/",
      "content": "Un portal independiente y plural.",
      "thumbnail": "",
      "labels": ["Periodismo", "Diario Digital", "Cordoba"],
      "type": "external",
      "source": "🔗 Medios de Comunicacion",
      "category": "Medios de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Biblioteca Popular Casa del Pueblo",
      "url": "https://www.facebook.com/biblioteca.casadelpueblo",
      "content": "Los esperamos martes, miercoles y jueves de 17:30 a 19:30 hs",
      "thumbnail": "",
      "labels": ["Biblioteca", "Libros", "Cordoba"],
      "type": "external",
      "source": "🔗 Educacion",
      "category": "Educacion",
      "date": "2026-05-16"
    },
    {
      "title": "Museo Genaro Perez",
      "url": "https://museogenaroperez.wordpress.com/",
      "content": "Excelente archivo digital de su colección de artes visuales",
      "thumbnail": "",
      "labels": ["Museo", "Bellas Artes", "Cordoba"],
      "type": "external",
      "source": "🔗 Educación",
      "category": "Educación",
      "date": "2026-05-16"
    },
    {
      "title": "Centro de Estudios Historicos Segreti",
      "url": "https://cehsegreti.org.ar/",
      "content": "Alianza estratégica entre el CONICET y el Centro de Estudios Históricos",
      "thumbnail": "",
      "labels": ["Biblioteca", "Historia", "CONICET"],
      "type": "external",
      "source": "🔗 educacion",
      "category": "educacion",
      "date": "2026-05-16"
    },
    {
      "title": "Agua de Oro Noticias",
      "url": "https://aguadeoronoticias.com.ar/",
      "content": "Diario Digital de las Sierras Chicas",
      "thumbnail": "",
      "labels": ["Periodismo", "Diario Digital", "Agua de Oro"],
      "type": "external",
      "source": "🔗 Medios de Comunicacion",
      "category": "Medios de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Prensa Red",
      "url": "https://prensared.org.ar/",
      "content": "Agencia de Noticias del CISPREN",
      "thumbnail": "",
      "labels": ["Informacion", "Agencia de Noticias", "Cordoba"],
      "type": "external",
      "source": "🔗 Periodismo",
      "category": "Periodismo",
      "date": "2026-05-16"
    },
    {
      "title": "Diario Tortuga",
      "url": "https://diariotortuga.com/",
      "content": "Cooperativa autogestionada que afianza y genera redes",
      "thumbnail": "",
      "labels": ["Periodismo", "Diario Digital", "Alta Gracia"],
      "type": "external",
      "source": "🔗 Medios de Comunicacion",
      "category": "Medios de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "El Milenio",
      "url": "https://elmilenio.info/",
      "content": "Proyecto Comunicativo Escolar - Conectamos Sierras Chicas.",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Sierras Chicas"],
      "type": "external",
      "source": "🔗 Medios de Comunicación",
      "category": "Medios de Comunicación",
      "date": "2026-05-16"
    },
    {
      "title": "Periodico Ñu Pora",
      "url": "https://periodiconupora.wordpress.com/",
      "content": "Periódico independiente de distribución gratuita de las Sierras Chicas. Informando desde 1992",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Sierras Chicas"],
      "type": "external",
      "source": "🔗 Medio de Comunicacion",
      "category": "Medio de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Info Sierras",
      "url": "https://infosierras.com/",
      "content": "Portal de noticias de las Sierras Chicas",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Sierras Chicas"],
      "type": "external",
      "source": "🔗 Medio de Comunicacion",
      "category": "Medio de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "DEMENDIOLAZA",
      "url": "https://demendiolaza.com.ar/",
      "content": "Portal de Noticias, Radio y Directorio comercial",
      "thumbnail": "",
      "labels": ["Radio Digital", "Musica", "Radio Online", "Mendiolaza"],
      "type": "external",
      "source": "🔗 Medio de Comunicacion",
      "category": "Medio de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Cordoba Interior Informa",
      "url": "https://cordobainteriorinforma.com/",
      "content": "Las noticias mas importantes del interior de Cordoba",
      "thumbnail": "",
      "labels": ["Diario Digital", "Periodismo", "Cordoba"],
      "type": "external",
      "source": "🔗 Medios de Comunicacion",
      "category": "Medios de Comunicacion",
      "date": "2026-05-16"
    },
    {
      "title": "Fundacion Ma.re.va",
      "url": "https://www.facebook.com/profile.php?id=100064513520238",
      "content": "Salón comunitario. Talleres para todas las edades. Feria. Trueque.",
      "thumbnail": "",
      "labels": ["ONG", "Salon Comunitario", "Centro Cultural", "Rio Ceballos"],
      "type": "external",
      "source": "🔗 Espacios Comunitarios",
      "category": "Espacios Comunitarios",
      "date": "2026-05-16"
    },
    {
      "title": "Biblioteca Popular Tere Andruetto",
      "url": "https://www.facebook.com/bbpptereandruetto",
      "content": "Biblioteca y centro cultural en Unquillo",
      "thumbnail": "",
      "labels": ["Centro Cultural", "Biblioteca", "Unquillo"],
      "type": "external",
      "source": "🔗 Educacion",
      "category": "Educacion",
      "date": "2026-05-16"
    },
    {
      "title": "Casa Museo Lino Spilimbergo",
      "url": "https://www.facebook.com/casamuseospilimbergo",
      "content": "Casa donde habitó Spilimbergo. Museo municipal dedicado a las artes visuales.",
      "thumbnail": "",
      "labels": ["Museo", "Bellas Artes", "Unquillo"],
      "type": "external",
      "source": "🔗 Espacio Cultural",
      "category": "Espacio Cultural",
      "date": "2026-05-16"
    },
    {
      "title": "Galeria Arte o Nada",
      "url": "https://www.facebook.com/arteonada",
      "content": "Galeria de arte, Atelier, Eventos culturales y Talleres de arte",
      "thumbnail": "",
      "labels": ["Centro Cultural", "Bellas Artes", "Unquillo"],
      "type": "external",
      "source": "🔗 Espacio Cultural",
      "category": "Espacio Cultural",
      "date": "2026-05-16"
    },
    {
      "title": "Arte Cba",
      "url": "https://artecba.com/",
      "content": "Espacio donde aprender, vivir y el arte promueve la venta y relación directa entre artistas y público",
      "thumbnail": "",
      "labels": ["Bellas Artes", "Espacio Cultural", "Cordoba"],
      "type": "external",
      "source": "🔗 Espacio Cultural",
      "category": "Espacio Cultural",
      "date": "2026-05-16"
    }
  ]
}